openapi: 3.0.0

info:
  title: embedding parallel languages with LASER
  version: 0.0.1

servers:
  - url: https://endpoint.ainize.ai/kmkwon94/ainize-laser/

paths:
  /vectorize:
    get:
      parameters:
        - name: q
          in: query
          default: Hello nice to meet you
          required: true
          allowReserved: true
          description: value that you want to type
        - name: lang
          in: query
          default: en
          required: true
          allowReserved: true
          description: value that you want to encode lagnuages
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        "400":
          description: Bad Request Error
        default:
          description: Unexpected Error
